config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/UniMainzGeo/LaMEM:
      branch: master
      repo: https://github.com/UniMainzGeo/LaMEM
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/UniMainzGeo/LaMEM git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-cinnabar-peccary.sh
        container: qc.acc_pokey-denim-wallaby
  QC.Doc:
    repos:
      github.com/UniMainzGeo/LaMEM find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-pink-turkey.sh
        container: qc.doc_sunny-purple-molly
      github.com/UniMainzGeo/LaMEM git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-jade-shrimp.sh
        container: qc.doc_skinny-celadon-tarantula
      github.com/UniMainzGeo/LaMEM markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-copper-eleuth.sh
        container: qc.doc_skinny-gamboge-capybara
  QC.Lic:
    repos:
      github.com/UniMainzGeo/LaMEM licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-peach-clam.sh
        container: qc.lic_smelly-viridian-spider
  QC.Sec:
    repos:
      github.com/UniMainzGeo/LaMEM bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-gold-rat.sh
        container: qc.sec_bumpy-chocolate-alligator
  QC.Sty:
    repos:
      github.com/UniMainzGeo/LaMEM flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-brown-dog.sh
        container: qc.sty_craggy-fuchsia-kingfisher
      github.com/UniMainzGeo/LaMEM jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-charcoal-insect.sh
        container: qc.sty_gummy-goldenrod-bulldog
  QC.Ver:
    repos:
      github.com/UniMainzGeo/LaMEM get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-linen-mau.sh
        container: qc.ver_snazzy-heliotrope-toucan
timeout: 5400
