config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/UniMainzGeo/LaMEM:
      branch: master
      repo: https://github.com/UniMainzGeo/LaMEM
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/UniMainzGeo/LaMEM git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-black-tarsier.sh
        container: qc.acc_stinky-carmine-mongrel
  QC.Doc:
    repos:
      github.com/UniMainzGeo/LaMEM find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-pink-indri.sh
        container: qc.doc_blurry-bronze-fox
      github.com/UniMainzGeo/LaMEM git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cerulean-weasel.sh
        container: qc.doc_pokey-russet-mandrill
  QC.Lic:
    repos:
      github.com/UniMainzGeo/LaMEM licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-mustard-barracuda.sh
        container: qc.lic_freaky-ecru-millipede
  QC.Sec:
    repos:
      github.com/UniMainzGeo/LaMEM bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-olivine-neanderthal.sh
        container: qc.sec_gummy-lilac-greyhound
  QC.Sty:
    repos:
      github.com/UniMainzGeo/LaMEM flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cornflower-chinook.sh
        container: qc.sty_squeaky-scarlet-husky
      github.com/UniMainzGeo/LaMEM jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-aqua-lynx.sh
        container: qc.sty_stuffy-rust-oyster
  QC.Ver:
    repos:
      github.com/UniMainzGeo/LaMEM get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-bronze-beaver.sh
        container: qc.ver_lanky-dandelion-emu
timeout: 5400
