config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/UniMainzGeo/LaMEM:
      branch: master
      repo: https://github.com/UniMainzGeo/LaMEM
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/UniMainzGeo/LaMEM git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-ultramarine-woodpecker.sh
        container: qc.acc_chummy-apricot-peccary
  QC.Doc:
    repos:
      github.com/UniMainzGeo/LaMEM find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cerulean-boar.sh
        container: qc.doc_hazy-ecru-moth
      github.com/UniMainzGeo/LaMEM git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-malachite-bloodhound.sh
        container: qc.doc_slimy-magenta-monster
      github.com/UniMainzGeo/LaMEM markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cobalt-donkey.sh
        container: qc.doc_randy-magnolia-crocodile
  QC.Lic:
    repos:
      github.com/UniMainzGeo/LaMEM licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-celadon-alligator.sh
        container: qc.lic_gamy-burgundy-toad
  QC.Sec:
    repos:
      github.com/UniMainzGeo/LaMEM bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-periwinkle-otter.sh
        container: qc.sec_wiggy-pumpkin-bloodhound
  QC.Sty:
    repos:
      github.com/UniMainzGeo/LaMEM flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-coral-angelfish.sh
        container: qc.sty_pasty-fuchsia-maltese
      github.com/UniMainzGeo/LaMEM jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-magenta-dunker.sh
        container: qc.sty_slaphappy-blue-moorhen
  QC.Ver:
    repos:
      github.com/UniMainzGeo/LaMEM get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-smalt-uakari.sh
        container: qc.ver_freaky-amaranth-angora
timeout: 5400
