config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/UniMainzGeo/LaMEM:
      branch: master
      repo: https://github.com/UniMainzGeo/LaMEM
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/UniMainzGeo/LaMEM git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-olive-chinook.sh
        container: qc.acc_squeaky-lime-coyote
  QC.Doc:
    repos:
      github.com/UniMainzGeo/LaMEM find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-carmine-dhole.sh
        container: qc.doc_paltry-ultramarine-bulldog
      github.com/UniMainzGeo/LaMEM git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-periwinkle-tetra.sh
        container: qc.doc_crappy-magenta-drever
      github.com/UniMainzGeo/LaMEM markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-platinum-nightingale.sh
        container: qc.doc_gamy-bronze-macaque
  QC.Lic:
    repos:
      github.com/UniMainzGeo/LaMEM licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-celadon-catfish.sh
        container: qc.lic_muzzy-myrtle-horse
  QC.Sec:
    repos:
      github.com/UniMainzGeo/LaMEM bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-puce-spitz.sh
        container: qc.sec_scanty-chocolate-bee
  QC.Sty:
    repos:
      github.com/UniMainzGeo/LaMEM flake8:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-pumpkin-sheepdog.sh
        container: qc.sty_jumpy-taupe-gorilla
      github.com/UniMainzGeo/LaMEM jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-malachite-spoonbill.sh
        container: qc.sty_ready-amethyst-woodlouse
  QC.Ver:
    repos:
      github.com/UniMainzGeo/LaMEM get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-burgundy-akita.sh
        container: qc.ver_craggy-tangerine-fousek
timeout: 5400
