config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/UniMainzGeo/LaMEM:
      branch: master
      repo: https://github.com/UniMainzGeo/LaMEM
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/UniMainzGeo/LaMEM git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-magenta-whale.sh
        container: qc.acc_ugly-copper-moorhen
  QC.Doc:
    repos:
      github.com/UniMainzGeo/LaMEM find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-green-moose.sh
        container: qc.doc_lanky-heliotrope-shrimp
      github.com/UniMainzGeo/LaMEM git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-tan-lobster.sh
        container: qc.doc_messy-lemon-akita
      github.com/UniMainzGeo/LaMEM markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-puce-rabbit.sh
        container: qc.doc_woozy-lime-stingray
  QC.Lic:
    repos:
      github.com/UniMainzGeo/LaMEM licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-beige-tetra.sh
        container: qc.lic_flaky-blue-gerbil
  QC.Sec:
    repos:
      github.com/UniMainzGeo/LaMEM bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-fuchsia-dog.sh
        container: qc.sec_jumpy-olive-skunk
  QC.Sty:
    repos:
      github.com/UniMainzGeo/LaMEM flake8:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-wisteria-ferret.sh
        container: qc.sty_silly-mustard-duck
      github.com/UniMainzGeo/LaMEM jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cornflower-shrew.sh
        container: qc.sty_zippy-eggplant-hippopotamus
  QC.Ver:
    repos:
      github.com/UniMainzGeo/LaMEM get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cerise-kiwi.sh
        container: qc.ver_greasy-cinnabar-chinook
timeout: 5400
