config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/UniMainzGeo/LaMEM:
      branch: master
      repo: https://github.com/UniMainzGeo/LaMEM
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/UniMainzGeo/LaMEM git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-carmine-zonkey.sh
        container: qc.acc_bluesy-wheat-bloodhound
  QC.Doc:
    repos:
      github.com/UniMainzGeo/LaMEM find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-lavender-stoat.sh
        container: qc.doc_homely-corn-quoll
      github.com/UniMainzGeo/LaMEM git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-puce-quetzal.sh
        container: qc.doc_stealthy-wisteria-mammoth
  QC.Lic:
    repos:
      github.com/UniMainzGeo/LaMEM licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-olivine-koala.sh
        container: qc.lic_lanky-cinnamon-newt
  QC.Sec:
    repos:
      github.com/UniMainzGeo/LaMEM bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-dandelion-deer.sh
        container: qc.sec_squeaky-olive-goose
  QC.Sty:
    repos:
      github.com/UniMainzGeo/LaMEM flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cream-kudu.sh
        container: qc.sty_pretty-viridian-seal
      github.com/UniMainzGeo/LaMEM jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cinnabar-starfish.sh
        container: qc.sty_skimpy-indigo-chin
  QC.Ver:
    repos:
      github.com/UniMainzGeo/LaMEM get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-gamboge-anteater.sh
        container: qc.ver_queasy-pink-gar
timeout: 5400
